-- Zoza Multiplayer setup — run once in Supabase SQL Editor
create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text unique not null check (char_length(code) between 4 and 12),
  host_id text not null,
  level int not null default 1 check(level between 1 and 100),
  hearts int not null default 0,
  status text not null default 'playing',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.players (
  id text primary key,
  room_code text not null references public.rooms(code) on delete cascade,
  name text not null check(char_length(name) between 1 and 24),
  avatar text not null default '👩🏻',
  x real not null default 40,
  y real not null default 280,
  online boolean not null default true,
  last_seen timestamptz not null default now()
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_code text not null references public.rooms(code) on delete cascade,
  player_id text not null,
  player_name text not null,
  body text not null check(char_length(body) between 1 and 300),
  created_at timestamptz not null default now()
);
create table if not exists public.game_state (
  room_code text primary key references public.rooms(code) on delete cascade,
  level int not null default 1,
  hearts jsonb not null default '[]'::jsonb,
  gate_open boolean not null default false,
  updated_at timestamptz not null default now()
);
create index if not exists players_room_idx on public.players(room_code);
create index if not exists messages_room_idx on public.messages(room_code,created_at);

alter table public.rooms enable row level security;
alter table public.players enable row level security;
alter table public.messages enable row level security;
alter table public.game_state enable row level security;

drop policy if exists "rooms_read" on public.rooms;
drop policy if exists "rooms_insert" on public.rooms;
drop policy if exists "rooms_update" on public.rooms;
drop policy if exists "players_all" on public.players;
drop policy if exists "messages_read" on public.messages;
drop policy if exists "messages_insert" on public.messages;
drop policy if exists "state_all" on public.game_state;

create policy "rooms_read" on public.rooms for select to anon using (true);
create policy "rooms_insert" on public.rooms for insert to anon with check (true);
create policy "rooms_update" on public.rooms for update to anon using (true) with check (true);
create policy "players_all" on public.players for all to anon using (true) with check (true);
create policy "messages_read" on public.messages for select to anon using (true);
create policy "messages_insert" on public.messages for insert to anon with check (true);
create policy "state_all" on public.game_state for all to anon using (true) with check (true);

alter publication supabase_realtime add table public.rooms;
alter publication supabase_realtime add table public.players;
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.game_state;


-- Browser client permissions (required because "Automatically expose new tables" is disabled)
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.rooms to anon, authenticated;
grant select, insert, update, delete on table public.players to anon, authenticated;
grant select, insert, update, delete on table public.messages to anon, authenticated;
grant select, insert, update, delete on table public.game_state to anon, authenticated;
grant usage, select on sequence public.messages_id_seq to anon, authenticated;
